trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - nodejsAuth
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: nodejsAuth/nodejs
      verbose: false
  - task: ArchiveFiles@2
    displayName: Archive nodejsAuth/nodejs
    inputs:
      rootFolderOrFile: nodejsAuth/nodejs
      archiveFile: Modules/nodejs.zip
  - task: S3Upload@1
    displayName: 'S3 Upload: private-bucket-modules-products'
    inputs:
      awsCredentials: 4881b3ec-4ad7-4247-8a52-ef6e117c10e1
      regionName: us-east-1
      bucketName: private-bucket-modules-products
      sourceFolder: Modules
      targetFolder: nodejsAuth

  - script: |
              sudo apt-get install jq      
              jq --version
    displayName: "SETUP: Install JQ"
    
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 4881b3ec-4ad7-4247-8a52-ef6e117c10e1
      regionName: "us-east-1"
      scriptType: "inline"
      inlineScript: |
          aws lambda publish-layer-version --layer-name ProductsLayerAuthorizer --description "Layer for Authorizer" --content S3Bucket=private-bucket-modules-products,S3Key=nodejsAuth/nodejs.zip --compatible-runtimes nodejs12.x;
          layer=$(aws lambda list-layer-versions --layer-name ProductsLayerAuthorizer | jq .LayerVersions[0].LayerVersionArn);
          aws lambda update-function-configuration --function-name LambdaAuthorizerUserProducts --layers $(echo $layer | sed 's:^.\(.*\).$:\1:');
          aws lambda update-function-configuration --function-name LambdaAuthorizerAdminProducts --layers $(echo $layer | sed 's:^.\(.*\).$:\1:');
